Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,5 +63,7 @@ jobs:
           sudo npm run build || { echo "npm run build failed"; exit 1; }
           echo "Copying files to /var/www/html/"
           sudo cp -r /home/ubuntu/lgn_server_frontend/build/* /var/www/html/lgnserfroend || { echo "File copy failed"; exit 1; }
+          echo "Reloading app using PM2"
+          pm2 reload all || { echo "PM2 reload failed"; exit 1; }
           echo "Deployment successful"
         EOF
